spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
server:
   port: 8400
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout:  60000
  ConnectTimeout:  60000
